### PR TITLE
Improve docs and getting started for new devs

### PR DESCRIPTION
**Pull request by madis**
# What's done?

Various improvements around readme docs and starting up the application.

1. Removes outdated instructions (e.g. related to figwheel)
  - check how much shorter it is https://github.com/district0x/ethlance/blob/1788be3077c96e2abe6272c43a2b89de6ae63723/README.md
2. Allows the whole app with all its dependencies to be started up with
   one step: `foreman start` or `invoker start`
3. Introduces `.tool-versions` and `asdf` version manager to get correct
   versions of `node`, `python`, `php` (and possibly others if needed)

        Because some dependencies are version sensitive, specifying (and thus
        unifying and documenting) the versions used would simplify starting
        development.

        `.tool-versions` is consumed by [asdf](https://github.com/asdf-vm/asdf)
        `Procfile` is used to start up all the services listed it with one
        command. E.g. [foreman](https://github.com/ddollar/foreman) or one of
        its ports (e.g. go, node, python, etc. https://github.com/ddollar/foreman#ports)

procfile-demo

# Initial (now outdated) pull request description

> Below is the initial pull request description for archive purposes
> Should it be removed?

## Intro

Hello. I'm trying to get ethlance running locally to have practical working example of an district0x application to tinker around with and learn about this project.

I'm following the readme but having some trouble which I hope some of you with more experience and already working versions could help me sort out.

As a result I would build up this pull request so that the readme (or some other source of information in this repository in a form of script or description) would allow a novice to get up to speed quickly. I'm in ideal position for this as you can only see something for the first time once :)

## Progress

1. `make check` - all success
2. `make deps` - all success
3. `make fig-dev-server` - fails
  - says `Build Id Error: "dev-server" is not a build-id in your configuration.`
  - when I remove `dev-server` from that step in Makefile I get
```
lein with-profile +dev-server figwheel
Warning: profile :dev-server not found.
Figwheel: Cutting some fruit, just a sec ...
Exception in thread "main" java.lang.NoSuchFieldError: ES3, compiling:(figwheel_sidecar/repl.clj:1:1)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        ...<rest of the output cropped>
```
  - Looked at circleci config and Makefile to follow the steps there but got no good ideas

## Questions

1. Do you recommend certain versions of Java/Clojure/Node?
2. Any advice how to deal with the `java.lang.NoSuchFieldError: ES3` error or how to proceed?
3. If someone would be up for a pairing session to set ethlance up, I could record and document and automate it. So next developers can have easier time.
4. Any other advice is also very welcome

> PS. Don't mind the node version bump. I just created it to make commit and be able to create pull request. If it's unnecessary or unproductive change, I'll remove it.

### CODE REVIEW

**Comment by madvas** [comment]
Hi, thank you for your notes. Yes, you're right, right now readme it's a bit outdated, because we migrated from lein to shadow-cljs, but we'll try to update it as we progress. Will check if version bump doesn't break anything.

**Comment by madis** [comment]
Thanks for the hint! I'll see how I can make it work using `shadow-cljs`!

**Comment by madvas** [comment]
currently we run: 
for server: 
```
cd ./server
yarn deps
yarn watch
```
for ui: 
```
cd ./ui
yarn deps
yarn watch
```
but before that you need to have running following: 
```
make testnet
make deploy
make postgres
make ipfs
```

**Comment by madis** [comment]
@madvas awesome, thanks a lot! I got it running. Now the fun can begin! I'll try to put my findings into more generally useful form. It was pretty much the steps you suggested + some dependencies (like nodejs, python, docker, etc.). 
Screenshot 2020-11-25 at 22 23 36

**Review by madvas — APPROVED** [review]
very good, thanks!

**Pull request merged**
